create DATABASE BMS_DB1;
use BMS_DB1;

show databases;
-- customer_personal_Info

CREATE TABLE CUSTOMER_PERSONAL_INFO
(
 CUSTOMER_ID VARCHAR(5),
 CUSTOMER_NAME VARCHAR(30),
 DATE_OF_BIRTH DATE,
 GUARDIAN_NAME VARCHAR(30),
 ADDRESS VARCHAR(50),
 CONTACT_NO BIGINT(10),
 MAIL_ID VARCHAR(30),
 GENDER CHAR(1),
 MARITAL_STATUS VARCHAR(10),
 IDENTIFICATION_DOC_TYPE VARCHAR(20),
 ID_DOC_NO VARCHAR(20),
 CITIZENSHIP VARCHAR(10),
 constraint CUST_PERS_INFO_PK primary key(CUSTOMER_ID)
 );
show tables;
-- CUSTOMER_REFERENCE_INFO

CREATE TABLE CUSTOMER_REFERENCE_INFO
(
 CUSTOMER_ID VARCHAR(5),
 REFERENCE_ACC_NAME VARCHAR(20),
 REFERENCE_ACC_NO BIGINT(16),
 REFERENCE_ACC_ADDRESS VARCHAR(50),
 RELATION VARCHAR(25),
 CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY(CUSTOMER_ID),
 CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
 );
show tables;
-- bank_info

CREATE TABLE BANK_INFO
(
IFSC_CODE VARCHAR(15),
BANK_NAME VARCHAR(25),
BRANCH_NAME VARCHAR(25),
CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
);

-- Account_INFO
CREATE TABLE ACCOUNT_INFO
(
ACCOUNT_NO BIGINT(16),
CUSTOMER_ID VARCHAR(5),
ACCOUNT_TYPE VARCHAR(10),
REGISTRATION_DATE DATE,
ACTIVATION_DATE DATE,
IFSC_CODE VARCHAR(10),
INTEREST DECIMAL(7,2),
INITIAL_DEPOSIT BIGINT(10),
constraint ACC_INFO_PK PRIMARY KEY(ACCOUNT_NO),
constraint ACC_INFO_PERS_FK foreign key(CUSTOMER_ID) REFERENCES CUSTOMER_REFERENCE_INFO(CUSTOMER_ID),
constraint ACC_INFO_BANK_FK FOREIGN KEY(IFSC_CODE) references BANK_INFO(IFSC_CODE)
);

show tables;

-- BANK_INFO

INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('HDL001','HDFC','PUNE');

INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('SBITN0123','SBI','THANE');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('SBITN0124','SBI','MUMBAI');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('ICIN123','ICICI','PUNE');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('ICIN242','ICICI','MUMBAI');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('UNI0ST','UNION','PUNE');

select * from bank_info;
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME, DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO, MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO ,CITIZENSHIP ) VALUES('C-001','JOHN','1984-05-03','PETER','NO-14 ST.MARKROAD,PUNE','9722227520','JOHN_123@GMAIL.COM','M','maried','AADHAR_CARD','8722-5276-3300','INDIAN');
select * from customer_personal_info;
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME, DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO, MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO ,CITIZENSHIP ) VALUES('C-002','PRANAV','2000-4-08-09','ROHAN','NO-20,MG ROAD,PUNE','9812578901','pranav_3@GMAIL.COM','M','Single','AADHAR_CARD','8856-5276-5241','INDIAN');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME, DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO, MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO ,CITIZENSHIP ) VALUES('C-003','ROHINI','1995-05-10','ANA','NO-16 TILAK RAOD,mumbai','8607271398','ROHINI_12@GMAIL.COM','F','maried','AADHAR_CARD','2936-8526-2541','INDIAN');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME, DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO, MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO ,CITIZENSHIP ) VALUES('C-004','KAJAL','2003-10-03','VISHAKHA','NO-05 NEHARU ROAD,THANE','8788332121','KJ_25@GMAIL.COM','F','single','AADHAR_CARD','2546-8956-2365','INDIAN');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME, DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO, MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO ,CITIZENSHIP ) VALUES('C-005','VISHAL','1990-08-19','JOHN','NO-10 HADAPSAR,PUNE','9970715120','VISHAL_098@GMAIL.COM','M','maried','AADHAR_CARD','9856-8956-5623','INDIAN');

select * from customer_personal_info;
show tables;SET FOREIGN_KEY_CHECKS=0;
INSERT INTO ACCOUNT_INFO(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,IFSC_CODE,INTEREST,INITIAL_DEPOSIT) VALUES( '123860901081','C-001','SAVING','2019-08-12','2019-08-12','ICTN123','3.2','55000');

SELECT * FROM ACCOUNT_INFO;
INSERT INTO ACCOUNT_INFO(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,IFSC_CODE,INTEREST,INITIAL_DEPOSIT) VALUES( '123860902216','C-002','SAVING','2019-08-12','2019-07-8','ICTN123','3.2','15000');
INSERT INTO ACCOUNT_INFO(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,IFSC_CODE,INTEREST,INITIAL_DEPOSIT) VALUES( '123860903818','C-003','CURRENT','2019-10-3','2019-10-12','SBITN0124','5.0','35000');
INSERT INTO ACCOUNT_INFO(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,IFSC_CODE,INTEREST,INITIAL_DEPOSIT) VALUES( '123860901920','C-004','SAVING','2019-08-12','2020-09-10','SBIN0123','3.2','50000');
INSERT INTO ACCOUNT_INFO(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,IFSC_CODE,INTEREST,INITIAL_DEPOSIT) VALUES( '123860900011','C-005','CURRENT','2019-08-12','2021-08-12','UNI0ST','5.0','150000');
SELECT * FROM ACCOUNT_INFO;
-- update value
update  ACCOUNT_INFO
SET CUSTOMER_ID = 'C-001'
WHERE ACCOUNT_NO = 123860901081;
-- sort
SELECT * FROM ACCOUNT_INFO 
order by customer_id asc;

insert into CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,RELATION)VALUES('1','ROHIT','123860901181','PUNE','FRIEND');
SELECT * FROM CUSTOMER_REFERENCE_INFO;
